name: ednet_core
description: Set of generic tools in modeling domain models based on domain-driven design and event storming
version: 0.0.1
homepage: https://github.com/ednet/ednet_core

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.7
  isar: ^3.0.5
  yaml: ^3.1.1
  test:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
